buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}
apply plugin: 'net.minecraftforge.gradle'

version = '0.1.0'
group = 'com.dogpound.prideperms'
archivesBaseName = 'PridePerms-1.12.2'
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
}

repositories { mavenCentral() }

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'
    compileOnly files('libs/mixinbooter-api.jar')
    compileOnly files('libs/sponge-mixin.jar')
}


jar {
    manifest {
        attributes([
            'FMLCorePlugin'               : 'com.dogpound.prideperms.PridePermsCore',
            'FMLCorePluginContainsFMLMod' : 'true',
            'ForceLoadAsMod'              : 'false',
            'MixinConfigs'                : 'prideperms.mixins.json'
        ])
    }
}
jar.finalizedBy('reobfJar')
